<a href="https://colab.research.google.com/github/gol99/Programming-Tutorials/blob/master/05_Exercises_Implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loop implementation
First, we define a function that computes the polynomial using a loop. We can add `print` statements in different parts of the function to ilustrate the steps.

In [ ]:
def p_loop(x, coef):
  print("Start loop implementation...")
  total = 0 # Keep track of value of the polynominal 

  # Iterate over the coefficients 
  for i, a in enumerate(coef):
    total = total + (a*(x**i))
    print("Adding the coefficient {} multiplied by x**{}".format(a,i))
  
  return total

# Matrix algebra implementation
There are a couple of functions from the `numpy` library that might be useful for the task at hand:
- [`numpy.cumprod`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cumprod.html): Return the cumulative product of elements along a given axis.
- [`numpy.dot`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html): Dot product of two arrays.

It's also a good idea to ilustrate how this function works using `print` statements.

In [ ]:
import numpy as np 

def p_ma(x, coef):
  print("Start matrix algebra implementation...")

  vecX = np.empty(len(coef))
  print("Create empty vector of xs:\n {}".format(vecX))

  vecX[0] = 1
  print("Assign 1 to the first element of the vector of xs:\n {}".format(vecX))

  vecX[1:] = x
  print("Assign x to the remaining elements of the the vector:\n {}".format(vecX))

  vecX = np.cumprod(vecX)
  print("Power each x to the appropiate exponent:\n {}".format(vecX)) 

  return np.dot(coef,vecX)

# Output comparison
Both implementation should yield almost identical results. We can write a little code to compare both implementations.

In [ ]:
n_coef = 5 # Number of coefficients 
LowerBound = 1 # Smallest possible 
UpperBound = 50 # Biggest possible coefficient
sample_coef = np.random.randint(LowerBound, UpperBound, size = n_coef) # Random coefficients between bounds 
print("The list of coefficients is \n {} \n".format(sample_coef))

eval_x = 2 # at which polynomial is evaluated 

print("The loop implementation returs {}".format(p_loop(eval_x,sample_coef)))
print("\n")
print("The matrix implementation returns {}".format(p_ma(eval_x,sample_coef)))

The list of coefficients is 
 [12 39 41 40  2] 

Start loop implementation...
Adding the coefficient 12 multiplied by x**0
Adding the coefficient 39 multiplied by x**1
Adding the coefficient 41 multiplied by x**2
Adding the coefficient 40 multiplied by x**3
Adding the coefficient 2 multiplied by x**4
The loop implementation returs 606


Start matrix algebra implementation...
Create empty vector of xs:
 [9.88e-324 1.63e-322 8.40e-323 8.89e-323 9.39e-323]
Assign 1 to the first element of the vector of xs:
 [1.00e+000 1.63e-322 8.40e-323 8.89e-323 9.39e-323]
Assign x to the remaining elements of the the vector:
 [1. 2. 2. 2. 2.]
Power each x to the appropiate exponent:
 [ 1.  2.  4.  8. 16.]
The matrix implementation returns 606.0


# Performance comparison
We want to know which of the two implementations is faster. In order to measure the time difference between the two implementations, first we need to create a version of the two functions that does **not** use any `print` statements. These statements consume time and we do not want our measure of time to be contaminted by that.

In [ ]:
def p_loop(x, coef):
  total = 0 # Keep track of value of the polynominal 

  # Iterate over the coefficients 
  for i, a in enumerate(coef):
    total = total + (a*(x**i))
  
  return total

In [ ]:
def p_ma(x, coef):
  vecX = np.empty(len(coef))
  vecX[0] = 1
  vecX[1:] = x
  vecX = np.cumprod(vecX)

  return np.dot(coef,vecX)

Now we want a *big* list of coefficients to evaluate both functions and a point in which to evaluate the polynomial.

In [ ]:
n_coef = 10000000 # Number of coefficients 
LowerBound = 1 # Smallest possible 
UpperBound = 50 # Biggest possible coefficient
sample_coef = np.random.randint(LowerBound, UpperBound, size = n_coef) # Random coefficients between bounds

eval_x = 1

In order to mesure time we need to use the [`time` library](https://docs.python.org/dev/library/time.html). For our loop implementation, we do:

In [ ]:
import time

start = time.time() 
loop_result = p_loop(eval_x, sample_coef) 
end = time.time() 

print("The loop implementation returs {} as output in {} seconds".format(loop_result, (end-start)))

The loop implementation returs 250026989 as output in 7.852407217025757 seconds


Same idea for the matrix algebra implementation:

In [ ]:
start = time.time() 
ma_result = p_ma(eval_x, sample_coef) 
end = time.time() 

print("The matrix implementation returs {} as output in {} seconds".format(ma_result, (end-start)))

The matrix implementation returs 24983883.0 as output in 0.02220773696899414 seconds


# Just-in-Time (JIT) compilation
There is a lot of material out there about how to code efficientlty (in terms of time performance) in Python. For example, [here](https://lectures.quantecon.org/py/numba.html) you can find some information on how to use the library `Numba` to improve performance. One of the many features of this library is the [Just-in-Time Compilation](https://numba.pydata.org/numba-doc/dev/reference/jit-compilation.html). We can use it to see if we can improve the performance of our functions.

In [ ]:
from numba import jit

p_loop_jit = jit(p_loop)
p_ma_jit = jit(p_ma, forceobj=True)

In [ ]:
start = time.time() 
loop_result = p_loop_jit(eval_x, sample_coef) 
end = time.time() 

print("The JIT loop implementation returs {} as output in {} seconds".format(loop_result, (end-start)))

The JIT loop implementation returs 250026989 as output in 0.34772229194641113 seconds


In [ ]:
start = time.time() 
ma_result = p_ma(eval_x, sample_coef) 
end = time.time() 

print("The matrix implementation returs {} as output in {} seconds".format(ma_result, (end-start)))

The matrix implementation returs 250026989.0 as output in 0.12703466415405273 seconds
